environment: dev

api:
  base_url: "https://v3.football.api-sports.io"
  rate_limit_per_minute: 10

postgres:
  host: localhost
  port: 5432
  db: sports_db

kafka:
  bootstrap_servers: "localhost:9092"

cassandra:
  hosts:
    - localhost
  keyspace: sports_streaming

spark:
  master: local[*]
  app_name: sports-platform-dev
